flags: {}
packages:
- .
extra-deps:
- hw-kafka-client-2.6.0
- git: https://github.com/nh2/hatrace.git
  commit: 4f7703a43a302dfff0b84cbfc37dbb70ccab4ec4
- git: https://github.com/nh2/linux-ptrace
  commit: 8969355c2e1ce095ef58acc5f2c5f8a4ea3f1645
- git: https://github.com/nh2/posix-waitpid.git
  commit: d2d7e06d85965dd022705d3d4e8348940afabb5f

allow-newer: true

resolver: lts-13.6
